name: Build LaTeX document and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: elew-cv.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: elew-cv.pdf

      - name: Create directory
        run: mkdir -p ./public

      - name: Move PDF to correct directory
        run: mv *.pdf ./public/

  deploy:
    needs: build_latex
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download PDF file
        uses: actions/download-artifact@v4
        with:
          name: PDF
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./public
